apiVersion: v1
kind: Secret
metadata:
  name: smeltry-operator-netbox
  namespace: {{ .Values.namespaceName }}
  labels:
    app.kubernetes.io/name: smeltry-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  netbox.token: {{ .Values.netbox.token | quote }}
