apiVersion: v1
kind: ServiceAccount
metadata:
  name: smeltry-operator
  namespace: {{ .Values.namespaceName }}
  labels:
    app.kubernetes.io/name: smeltry-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
