apiVersion: v1
kind: Service
metadata:
  name: smeltry-operator-metrics
  namespace: {{ .Values.namespaceName }}
  labels:
    app.kubernetes.io/name: smeltry-operator
    app.kubernetes.io/component: metrics
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    app.kubernetes.io/name: smeltry-operator
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
